name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
          architecture: x64

      - uses: actions/checkout@v2

      - name: Download UPX
        uses: i3h/download-release-asset@v1.3.2
        with:
          owner: upx
          repo: upx
          tag: v3.96
          file: upx-3.96-win64.zip

      - name: Extract UPX
        run: |
          7z x upx-3.96-win64.zip
          copy upx-3.96-win64\upx.exe upx.exe

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install

      - name: Test
        run: python -m pipenv run tox

      - name: Build
        run: python -m pipenv run build_win_installer.bat

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/shortcircuit.exe
